baseUrl = "https://patricklawler.netlify.app"
languageCode = "en-us"
title = "Patrick Lawler"
theme = "anubis"

[permalinks]
posts = "/posts/:year/:month/:slug/"

[menu]
[[menu.main]]
name = "Home"
identifier = "home"
url = "/"
weight = 1

[[menu.main]]
identifier = "now"
name = "Now"
url = "/now/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 4

[params]
author = "Patrick Lawler"
style = "dark"